apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service-nodeport
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 80  # Puerto del servicio
    targetPort: 80  # Puerto en el contenedor
  type: NodePort  # Se utiliza NodePort en lugar de LoadBalancer
