apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 4;
    events { worker_connections 1024; }
    http {
      server {
        listen 80;
        server_name my-nginx-app;
        location / {
          proxy_pass http://localhost:8080;
        }
      }
    }
